# Generated by Django 4.2 on 2023-07-19 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.IntegerField()),
                ('region', models.CharField(choices=[('ar', 'ARUSHA'), ('dar', 'DAR'), ('dom', 'DODOMA'), ('kgm', 'KIGOMA'), ('klm', 'KILIMANJARO'), ('mby', 'MBEYA'), ('mza', 'MWANZA'), ('online', 'ONLINE'), ('znz', 'ZANZIBAR')], default='dar', max_length=20)),
                ('family_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], max_length=10)),
                ('month_B', models.DateField(choices=[('JAN', 'JANUARY'), ('FEB', 'FEBRUARY'), ('MAR', 'MARCH'), ('APR', 'APRIL'), ('MAY', 'MAY'), ('JUN', 'JUNE'), ('JUL', 'JULY'), ('AUG', 'AUGUST'), ('SEPT', 'SEPTEMBER'), ('OCT', 'OCTOBER'), ('NOV', 'NOVEMBER'), ('DEC', 'DECEMBER')], max_length=255)),
                ('day_B', models.PositiveIntegerField()),
                ('year_B', models.PositiveIntegerField()),
                ('birth_city', models.CharField(max_length=255)),
                ('birth_country', models.CharField(max_length=255)),
                ('eligibility_country', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('highest_education', models.CharField(choices=[('PR', 'PRIMARY SCH'), ('HSND', 'HIGH SCH NO DGR'), ('HSD', 'HIGH SCH DGR'), ('VS', 'VOCATIONAL SCH'), ('UC', 'SOME UNIVERSITY COURSES'), ('UD', 'UNIVERSITY DEGREE'), ('GRC', 'SOME GRADUATE LEVEL COURSES'), ('MSC', 'MASTERS'), ('DOC', 'SOME DOCTORATE LEVEL COURSES'), ('PHD', 'DOCTORATE DEGREE')], max_length=255)),
                ('no_of_children', models.PositiveIntegerField(null=True)),
                ('marital_status', models.CharField(choices=[('single', 'SINGLE'), ('married', 'MARRIED'), ('divorced', 'DIVORCED')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Spouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], max_length=10)),
                ('month_B', models.DateField(choices=[('JAN', 'JANUARY'), ('FEB', 'FEBRUARY'), ('MAR', 'MARCH'), ('APR', 'APRIL'), ('MAY', 'MAY'), ('JUN', 'JUNE'), ('JUL', 'JULY'), ('AUG', 'AUGUST'), ('SEPT', 'SEPTEMBER'), ('OCT', 'OCTOBER'), ('NOV', 'NOVEMBER'), ('DEC', 'DECEMBER')], max_length=255)),
                ('day_B', models.PositiveIntegerField()),
                ('year_B', models.PositiveIntegerField()),
                ('birth_city', models.CharField(max_length=255)),
                ('birth_country', models.CharField(max_length=255)),
                ('main_applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataentry.mainapplicant')),
            ],
        ),
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dress_color', models.CharField(max_length=50)),
                ('family_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], max_length=10)),
                ('month_B', models.DateField(choices=[('JAN', 'JANUARY'), ('FEB', 'FEBRUARY'), ('MAR', 'MARCH'), ('APR', 'APRIL'), ('MAY', 'MAY'), ('JUN', 'JUNE'), ('JUL', 'JULY'), ('AUG', 'AUGUST'), ('SEPT', 'SEPTEMBER'), ('OCT', 'OCTOBER'), ('NOV', 'NOVEMBER'), ('DEC', 'DECEMBER')], max_length=255)),
                ('day_B', models.PositiveIntegerField()),
                ('year_B', models.PositiveIntegerField()),
                ('birth_city', models.CharField(max_length=255)),
                ('birth_country', models.CharField(max_length=255)),
                ('main_applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataentry.mainapplicant')),
            ],
        ),
    ]
