# Generated by Django 4.2 on 2023-09-09 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicant',
            options={'ordering': ('family_name',), 'verbose_name_plural': 'Applicant'},
        ),
        migrations.AlterModelOptions(
            name='dependant',
            options={'ordering': ('family_name',), 'verbose_name_plural': 'Dependant'},
        ),
    ]
