# Generated by Django 4.2 on 2023-07-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='children',
            options={'ordering': ('family_name',), 'verbose_name_plural': 'Children'},
        ),
        migrations.AlterModelOptions(
            name='mainapplicant',
            options={'ordering': ('family_name',), 'verbose_name_plural': 'MainApplicant'},
        ),
        migrations.AlterModelOptions(
            name='spouse',
            options={'ordering': ('family_name',), 'verbose_name_plural': 'Spouse'},
        ),
        migrations.AlterField(
            model_name='children',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='children',
            name='month_B',
            field=models.DateField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mainapplicant',
            name='birth_city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mainapplicant',
            name='birth_country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mainapplicant',
            name='day_B',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mainapplicant',
            name='eligibility_country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mainapplicant',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mainapplicant',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mainapplicant',
            name='highest_education',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mainapplicant',
            name='marital_status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mainapplicant',
            name='month_B',
            field=models.PositiveIntegerField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mainapplicant',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mainapplicant',
            name='region',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='mainapplicant',
            name='year_B',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='spouse',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='spouse',
            name='month_B',
            field=models.DateField(max_length=255),
        ),
    ]
