# Generated by Django 4.2 on 2023-09-09 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0002_alter_applicant_options_alter_dependant_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicant',
            options={'ordering': ('family_name',), 'verbose_name_plural': 'Applicants'},
        ),
        migrations.AlterModelOptions(
            name='dependant',
            options={'ordering': ('family_name',), 'verbose_name_plural': 'Dependants'},
        ),
    ]
