# Generated by Django 4.2 on 2023-07-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0002_alter_children_options_alter_mainapplicant_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='children',
            name='month_B',
            field=models.PositiveBigIntegerField(max_length=255),
        ),
        migrations.AlterField(
            model_name='spouse',
            name='month_B',
            field=models.PositiveIntegerField(max_length=255),
        ),
    ]
