# Generated by Django 4.2 on 2023-09-09 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0003_alter_applicant_options_alter_dependant_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='region',
            field=models.CharField(choices=[('ar', 'ARUSHA'), ('dar', 'DAR'), ('dom', 'DODOMA'), ('kgm', 'KIGOMA'), ('klm', 'KILIMANJARO'), ('mby', 'MBEYA'), ('mza', 'MWANZA'), ('nrb', 'NAIROBI'), ('online', 'ONLINE'), ('znz', 'ZANZIBAR')], max_length=20),
        ),
        migrations.AlterField(
            model_name='dependant',
            name='main_applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_dependant', to='dataentry.applicant'),
        ),
    ]
