# Generated by Django 4.2 on 2023-09-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0004_alter_applicant_region_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dependant',
            old_name='dress_color',
            new_name='dress_or_shirt_color',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='region',
            field=models.CharField(choices=[('ar', 'ARUSHA'), ('dar', 'DAR'), ('dom', 'DODOMA'), ('kgm', 'KIGOMA'), ('klm', 'KILIMANJARO'), ('mby', 'MBEYA'), ('mza', 'MWANZA'), ('kny', 'KENYA'), ('online', 'ONLINE'), ('znz', 'ZANZIBAR')], max_length=20),
        ),
    ]
