# Generated by Django 4.2 on 2023-07-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0004_alter_children_month_b_alter_spouse_month_b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainapplicant',
            name='month_B',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
