# Generated by Django 4.2 on 2023-09-24 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0005_rename_dress_color_dependant_dress_or_shirt_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='application_number',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='day_B',
            field=models.PositiveIntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31')]),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='month_B',
            field=models.CharField(choices=[('1', 'JANUARY'), ('2', 'FEBRUARY'), ('3', 'MARCH'), ('4', 'APRIL'), ('5', 'MAY'), ('6', 'JUNE'), ('7', 'JULY'), ('8', 'AUGUST'), ('9', 'SEPTEMBER'), ('10', 'OCTOBER'), ('11', 'NOVEMBER'), ('12', 'DECEMBER')], max_length=100),
        ),
        migrations.AlterField(
            model_name='dependant',
            name='day_B',
            field=models.PositiveIntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31')]),
        ),
        migrations.AlterField(
            model_name='dependant',
            name='month_B',
            field=models.CharField(choices=[('1', 'JANUARY'), ('2', 'FEBRUARY'), ('3', 'MARCH'), ('4', 'APRIL'), ('5', 'MAY'), ('6', 'JUNE'), ('7', 'JULY'), ('8', 'AUGUST'), ('9', 'SEPTEMBER'), ('10', 'OCTOBER'), ('11', 'NOVEMBER'), ('12', 'DECEMBER')], max_length=100),
        ),
    ]
