# Generated by Django 4.2 on 2023-09-24 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dataentry', '0006_alter_applicant_application_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='day_B',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='dependant',
            name='day_B',
            field=models.PositiveIntegerField(),
        ),
    ]
