# Generated by Django 4.2 on 2023-09-29 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0008_dependant_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependant',
            name='user',
        ),
    ]
